# Generated by Django 5.2.7 on 2026-03-20 13:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_court_to_fk(apps, schema_editor):
    """Convert old court CharField values to Court FK. Create courts for existing values."""
    Case = apps.get_model("cases", "Case")
    Court = apps.get_model("cases", "Court")
    for case in Case.objects.all():
        old_court = case.court_old
        if old_court and old_court.strip():
            court, _ = Court.objects.get_or_create(
                name=old_court.strip(), defaults={"name_en": old_court.strip(), "order": 999}
            )
            case.court_new = court
            case.save(update_fields=["court_new"])


def reverse_migrate_court(apps, schema_editor):
    """Revert: copy court name back to CharField (for rollback only)."""
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.select_related("court_new").all():
        if case.court_new:
            case.court_old = case.court_new.name
            case.save(update_fields=["court_old"])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='अदालतको नाम')),
                ('name_en', models.CharField(blank=True, help_text='Optional English name', max_length=255, verbose_name='अदालतको नाम (अङ्ग्रेजी)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in dropdown', verbose_name='क्रम')),
            ],
            options={
                'verbose_name': 'अदालत',
                'verbose_name_plural': 'अदालतहरू',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='court_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cases.court', verbose_name='अदालत'),
        ),
        migrations.RenameField(
            model_name='case',
            old_name='court',
            new_name='court_old',
        ),
        migrations.RunPython(migrate_court_to_fk, reverse_migrate_court),
        migrations.RemoveField(
            model_name='case',
            name='court_old',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='court_new',
            new_name='court',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'मुद्दा', 'verbose_name_plural': 'मुद्दाहरू'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='मुद्दा नम्बर'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('criminal', 'फौजदारी'), ('civil', 'दीवानी'), ('family', 'पारिवारिक'), ('corporate', 'कर्पोरेट'), ('other', 'अन्य')], max_length=20, verbose_name='मुद्दाको प्रकार'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='ग्राहकको नाम'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='case',
            name='filed_date',
            field=models.DateField(blank=True, null=True, verbose_name='दाखिल मिति'),
        ),
        migrations.AlterField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True, verbose_name='नोटहरू'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'पेन्डिङ'), ('ongoing', 'चलिरहेको'), ('closed', 'बन्द')], default='pending', max_length=20, verbose_name='स्थिति'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='अद्यावधिक मिति'),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='कागजातको नाम')),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/', verbose_name='फाइल')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='अपलोड मिति')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='मुद्दा')),
            ],
            options={
                'verbose_name': 'मुद्दाको कागजात',
                'verbose_name_plural': 'मुद्दाका कागजातहरू',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
